root = "."
tmp_dir = "tmp/air"

[build]
cmd = "go build -o ./tmp/air/go-fiber-starter.exe ./cmd"
bin = "tmp/air/go-fiber-starter.exe"
full_bin = "tmp/air/go-fiber-starter.exe"
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["tmp", "bin", "log", "docs", ".git", ".gocache", ".gomodcache"]
delay = 500
stop_on_error = true

[log]
time = true

[screen]
clear_on_rebuild = true
